const fs = require('fs');

const path = 'src/i18n.ts';
let content = fs.readFileSync(path, 'utf8');

const translations = {
  en: `      comparison: {
        title: 'Why EasyDubbing is',
        titleHighlight: 'The Smartest Choice',
        subtitle1: 'More value. More features.',
        subtitle2: 'One simple price.',
        seeHow: 'See how',
        weCompare: 'we compare',
        bestValue: 'Best Value',
        limitedCostly: 'Limited & Costly',
        usageBased: 'Usage-Based Pricing',
        langSupported: 'Languages Supported',
        dubbingMinutes: 'AI Dubbing Minutes',
        unlimited: 'Unlimited',
        noLimits: '(No limits)',
        minPerMonth: '100 min / month',
        creatorPlan: '(Creator Plan)',
        payPerSecond: 'Pay per second',
        noMonthlyMin: '(No monthly minutes)',
        pricing: 'Pricing (Starting From)',
        perMonth: '/month',
        orLifetime: 'or €315 Lifetime',
        limitedMin: '(Limited minutes)',
        estimated: '(Estimated)',
        localProc: 'Local Processing',
        limited: 'Limited',
        no: 'No',
        yes: 'Yes',
        cloning: 'High-Fidelity Cloning',
        notIncluded: 'Not Included',
        higherPlans: '(Higher plans only)',
        complexFees: 'Complex Usage Fees',
        perMinCharges: '(Per minute charges)',
        perFrameCharges: '(Per frame charges)',
        cancelAnytime: 'Cancel Anytime',
        storage: 'Storage Included',
        notSpecified: 'Not Specified',
        lifetimeOption: 'Lifetime Plan Option',
        lifetimePro: '(Lifetime Pro License)',
        winnerTitle: 'The Winner',
        winnerSubtitle: 'For Creators & Professionals',
        bestChoice: 'The Best Choice',
        bestChoiceDesc: 'More features. Better price. Maximum freedom.',
        expensiveLimited: 'Expensive & Limited',
        expensiveLimitedDesc: 'Limited minutes. Extra charges.',
        mostExpensive: 'Most Expensive',
        mostExpensiveDesc: 'Pay-per-frame model. Very high monthly costs.',
        ctaTitle: 'Stop overpaying for AI dubbing.',
        ctaDesc: 'EasyDubbing gives you more features, more freedom, and a one-time lifetime option.',
        tryToday: 'Try EasyDubbing Today',
        professionalDubbing: 'Professional AI Dubbing'
      }`,
  fr: `      comparison: {
        title: 'Pourquoi EasyDubbing est',
        titleHighlight: 'Le Choix le Plus Intelligent',
        subtitle1: 'Plus de valeur. Plus de fonctionnalités.',
        subtitle2: 'Un prix simple.',
        seeHow: 'Découvrez comment',
        weCompare: 'nous nous comparons',
        bestValue: 'Meilleure Valeur',
        limitedCostly: 'Limité et Coûteux',
        usageBased: "Tarification à l'usage",
        langSupported: 'Langues Supportées',
        dubbingMinutes: 'Minutes de Doublage IA',
        unlimited: 'Illimité',
        noLimits: '(Sans limites)',
        minPerMonth: '100 min / mois',
        creatorPlan: '(Plan Créateur)',
        payPerSecond: 'Payer à la seconde',
        noMonthlyMin: '(Aucune minute mensuelle)',
        pricing: 'Tarifs (À partir de)',
        perMonth: '/mois',
        orLifetime: 'ou 315 € à Vie',
        limitedMin: '(Minutes limitées)',
        estimated: '(Estimé)',
        localProc: 'Traitement Local',
        limited: 'Limité',
        no: 'Non',
        yes: 'Oui',
        cloning: 'Clonage Haute Fidélité',
        notIncluded: 'Non Inclus',
        higherPlans: '(Plans supérieurs uniquement)',
        complexFees: "Frais d'Usage Complexes",
        perMinCharges: '(Frais par minute)',
        perFrameCharges: '(Frais par image)',
        cancelAnytime: 'Annulez à tout moment',
        storage: 'Stockage Inclus',
        notSpecified: 'Non Spécifié',
        lifetimeOption: 'Option de Plan à Vie',
        lifetimePro: '(Licence Pro à Vie)',
        winnerTitle: 'Le Gagnant',
        winnerSubtitle: 'Pour Créateurs et Professionnels',
        bestChoice: 'Le Meilleur Choix',
        bestChoiceDesc: 'Plus de fonctionnalités. Meilleur prix. Liberté maximale.',
        expensiveLimited: 'Cher et Limité',
        expensiveLimitedDesc: 'Minutes limitées. Frais supplémentaires.',
        mostExpensive: 'Le Plus Cher',
        mostExpensiveDesc: "Modèle à l'image. Coûts mensuels très élevés.",
        ctaTitle: 'Arrêtez de payer trop cher pour le doublage IA.',
        ctaDesc: 'EasyDubbing vous offre plus de fonctionnalités, plus de liberté, et une option à vie en un seul paiement.',
        tryToday: "Essayez EasyDubbing Aujourd'hui",
        professionalDubbing: 'Doublage IA Professionnel'
      }`,
  es: `      comparison: {
        title: 'Por qué EasyDubbing es',
        titleHighlight: 'La Decisión Más Inteligente',
        subtitle1: 'Más valor. Más funciones.',
        subtitle2: 'Un precio simple.',
        seeHow: 'Vea cómo',
        weCompare: 'nos comparamos',
        bestValue: 'Mejor Valor',
        limitedCostly: 'Limitado y Costoso',
        usageBased: 'Precio por Uso',
        langSupported: 'Idiomas Soportados',
        dubbingMinutes: 'Minutos de Doblaje de IA',
        unlimited: 'Ilimitado',
        noLimits: '(Sin límites)',
        minPerMonth: '100 min / mes',
        creatorPlan: '(Plan Creador)',
        payPerSecond: 'Pago por segundo',
        noMonthlyMin: '(Sin minutos mensuales)',
        pricing: 'Precios (Desde)',
        perMonth: '/mes',
        orLifetime: 'o 315 € de por vida',
        limitedMin: '(Minutos limitados)',
        estimated: '(Estimado)',
        localProc: 'Procesamiento Local',
        limited: 'Limitado',
        no: 'No',
        yes: 'Sí',
        cloning: 'Clonación de Alta Fidelidad',
        notIncluded: 'No Incluido',
        higherPlans: '(Solo planes superiores)',
        complexFees: 'Cargos de Uso Complejos',
        perMinCharges: '(Cargos por minuto)',
        perFrameCharges: '(Cargos por cuadro)',
        cancelAnytime: 'Cancelar en cualquier momento',
        storage: 'Almacenamiento Incluido',
        notSpecified: 'No Especificado',
        lifetimeOption: 'Opción de Plan de por Vida',
        lifetimePro: '(Licencia Pro de por Vida)',
        winnerTitle: 'El Ganador',
        winnerSubtitle: 'Para Creadores y Profesionales',
        bestChoice: 'La Mejor Elección',
        bestChoiceDesc: 'Más funciones. Mejor precio. Máxima libertad.',
        expensiveLimited: 'Caro y Limitado',
        expensiveLimitedDesc: 'Minutos limitados. Cargos extra.',
        mostExpensive: 'Más Caro',
        mostExpensiveDesc: 'Modelo por cuadro. Costos mensuales muy altos.',
        ctaTitle: 'Deje de pagar de más por doblaje de IA.',
        ctaDesc: 'EasyDubbing le brinda más funciones, más libertad y una opción única de por vida.',
        tryToday: 'Pruebe EasyDubbing Hoy',
        professionalDubbing: 'Doblaje IA Profesional'
      }`,
  it: `      comparison: {
        title: 'Perché EasyDubbing è',
        titleHighlight: 'La Scelta Più Intelligente',
        subtitle1: 'Più valore. Più funzionalità.',
        subtitle2: 'Un prezzo semplice.',
        seeHow: 'Scopri come',
        weCompare: 'ci confrontiamo',
        bestValue: 'Miglior Valore',
        limitedCostly: 'Limitato e Costoso',
        usageBased: 'Prezzi a Consumo',
        langSupported: 'Lingue Supportate',
        dubbingMinutes: 'Minuti di Doppiaggio IA',
        unlimited: 'Illimitato',
        noLimits: '(Senza limiti)',
        minPerMonth: '100 min / mese',
        creatorPlan: '(Piano Creator)',
        payPerSecond: 'Paga al secondo',
        noMonthlyMin: '(Nessun minuto mensile)',
        pricing: 'Prezzi (A partire da)',
        perMonth: '/mese',
        orLifetime: 'o €315 a Vita',
        limitedMin: '(Minuti limitati)',
        estimated: '(Stimato)',
        localProc: 'Elaborazione Locale',
        limited: 'Limitato',
        no: 'No',
        yes: 'Sì',
        cloning: 'Clonazione ad Alta Fedeltà',
        notIncluded: 'Non Incluso',
        higherPlans: '(Solo piani superiori)',
        complexFees: 'Costi di Utilizzo Complessi',
        perMinCharges: '(Addebiti al minuto)',
        perFrameCharges: '(Addebiti al frame)',
        cancelAnytime: 'Annulla in qualsiasi momento',
        storage: 'Spazio Incluso',
        notSpecified: 'Non Specificato',
        lifetimeOption: 'Opzione Piano a Vita',
        lifetimePro: '(Licenza Pro a Vita)',
        winnerTitle: 'Il Vincitore',
        winnerSubtitle: 'Per Creatori e Professionisti',
        bestChoice: 'La Scelta Migliore',
        bestChoiceDesc: 'Più funzionalità. Prezzo migliore. Massima libertà.',
        expensiveLimited: 'Costoso e Limitato',
        expensiveLimitedDesc: 'Minuti limitati. Costi extra.',
        mostExpensive: 'Più Costoso',
        mostExpensiveDesc: 'Modello per frame. Costi mensili molto alti.',
        ctaTitle: 'Smetti di pagare troppo per il doppiaggio IA.',
        ctaDesc: "EasyDubbing ti offre più funzionalità, più libertà e un'opzione una tantum a vita.",
        tryToday: 'Prova EasyDubbing Oggi',
        professionalDubbing: 'Doppiaggio IA Professionale'
      }`,
  de: `      comparison: {
        title: 'Warum EasyDubbing die',
        titleHighlight: 'Smarteste Wahl ist',
        subtitle1: 'Mehr Wert. Mehr Funktionen.',
        subtitle2: 'Ein einfacher Preis.',
        seeHow: 'Sehen Sie,',
        weCompare: 'wie wir abschneiden',
        bestValue: 'Bester Wert',
        limitedCostly: 'Begrenzt & Teuer',
        usageBased: 'Nutzungsbasierter Preis',
        langSupported: 'Unterstützte Sprachen',
        dubbingMinutes: 'KI-Dubbing-Minuten',
        unlimited: 'Unbegrenzt',
        noLimits: '(Keine Limits)',
        minPerMonth: '100 Min. / Monat',
        creatorPlan: '(Creator-Plan)',
        payPerSecond: 'Pro Sekunde zahlen',
        noMonthlyMin: '(Keine monatlichen Minuten)',
        pricing: 'Preise (Ab)',
        perMonth: '/Monat',
        orLifetime: 'oder 315 € Lifetime',
        limitedMin: '(Begrenzte Minuten)',
        estimated: '(Geschätzt)',
        localProc: 'Lokale Verarbeitung',
        limited: 'Begrenzt',
        no: 'Nein',
        yes: 'Ja',
        cloning: 'High-Fidelity Cloning',
        notIncluded: 'Nicht Enthalten',
        higherPlans: '(Nur höhere Pläne)',
        complexFees: 'Komplexe Nutzungsgebühren',
        perMinCharges: '(Pro-Minute-Gebühren)',
        perFrameCharges: '(Pro-Frame-Gebühren)',
        cancelAnytime: 'Jederzeit kündbar',
        storage: 'Speicher Inklusive',
        notSpecified: 'Nicht Angegeben',
        lifetimeOption: 'Lifetime-Plan-Option',
        lifetimePro: '(Lifetime Pro-Lizenz)',
        winnerTitle: 'Der Gewinner',
        winnerSubtitle: 'Für Creator & Profis',
        bestChoice: 'Die Beste Wahl',
        bestChoiceDesc: 'Mehr Funktionen. Besserer Preis. Maximale Freiheit.',
        expensiveLimited: 'Teuer & Begrenzt',
        expensiveLimitedDesc: 'Begrenzte Minuten. Extra-Gebühren.',
        mostExpensive: 'Am Teuersten',
        mostExpensiveDesc: 'Pay-per-Frame-Modell. Sehr hohe monatliche Kosten.',
        ctaTitle: 'Hören Sie auf, zu viel für KI-Dubbing zu zahlen.',
        ctaDesc: 'EasyDubbing bietet Ihnen mehr Funktionen, mehr Freiheit und eine einmalige Lifetime-Option.',
        tryToday: 'EasyDubbing Heute Testen',
        professionalDubbing: 'Professionelles KI-Dubbing'
      }`,
  ru: `      comparison: {
        title: 'Почему EasyDubbing -',
        titleHighlight: 'Самый умный выбор',
        subtitle1: 'Больше ценности. Больше функций.',
        subtitle2: 'Одна простая цена.',
        seeHow: 'Посмотрите,',
        weCompare: 'как мы сравниваемся',
        bestValue: 'Лучшая цена',
        limitedCostly: 'Ограничено и дорого',
        usageBased: 'Оплата за использование',
        langSupported: 'Поддерживаемые языки',
        dubbingMinutes: 'Минуты ИИ-дубляжа',
        unlimited: 'Безлимитно',
        noLimits: '(Без ограничений)',
        minPerMonth: '100 мин / месяц',
        creatorPlan: '(План Creator)',
        payPerSecond: 'Оплата за секунду',
        noMonthlyMin: '(Без ежемесячных минут)',
        pricing: 'Цены (Начиная от)',
        perMonth: '/месяц',
        orLifetime: 'или €315 Пожизненно',
        limitedMin: '(Ограниченные минуты)',
        estimated: '(Примерно)',
        localProc: 'Локальная обработка',
        limited: 'Ограничено',
        no: 'Нет',
        yes: 'Да',
        cloning: 'Высокоточное клонирование',
        notIncluded: 'Не включено',
        higherPlans: '(Только в дорогих планах)',
        complexFees: 'Сложные комиссии',
        perMinCharges: '(Плата за минуту)',
        perFrameCharges: '(Плата за кадр)',
        cancelAnytime: 'Отмена в любое время',
        storage: 'Включенное хранилище',
        notSpecified: 'Не указано',
        lifetimeOption: 'Пожизненный план',
        lifetimePro: '(Пожизненная лицензия Pro)',
        winnerTitle: 'Победитель',
        winnerSubtitle: 'Для авторов и профессионалов',
        bestChoice: 'Лучший выбор',
        bestChoiceDesc: 'Больше функций. Лучшая цена. Максимальная свобода.',
        expensiveLimited: 'Дорого и ограничено',
        expensiveLimitedDesc: 'Ограниченные минуты. Доп. платежи.',
        mostExpensive: 'Самый дорогой',
        mostExpensiveDesc: 'Модель оплаты за кадр. Очень высокие расходы.',
        ctaTitle: 'Хватит переплачивать за ИИ-дубляж.',
        ctaDesc: 'EasyDubbing дает вам больше функций, больше свободы и возможность единоразовой оплаты навсегда.',
        tryToday: 'Попробуйте EasyDubbing сегодня',
        professionalDubbing: 'Профессиональный ИИ-дубляж'
      }`,
  ar: `      comparison: {
        title: 'لماذا EasyDubbing هو',
        titleHighlight: 'الخيار الأذكى',
        subtitle1: 'قيمة أكبر. ميزات أكثر.',
        subtitle2: 'سعر واحد بسيط.',
        seeHow: 'انظر كيف',
        weCompare: 'نقارن',
        bestValue: 'أفضل قيمة',
        limitedCostly: 'محدود ومكلف',
        usageBased: 'الدفع حسب الاستخدام',
        langSupported: 'اللغات المدعومة',
        dubbingMinutes: 'دقائق دبلجة الذكاء الاصطناعي',
        unlimited: 'غير محدود',
        noLimits: '(بدون قيود)',
        minPerMonth: '100 دقيقة / شهر',
        creatorPlan: '(خطة منشئ المحتوى)',
        payPerSecond: 'الدفع بالثانية',
        noMonthlyMin: '(لا توجد دقائق شهرية)',
        pricing: 'الأسعار (تبدأ من)',
        perMonth: '/شهر',
        orLifetime: 'أو 315 يورو مدى الحياة',
        limitedMin: '(دقائق محدودة)',
        estimated: '(مُقدر)',
        localProc: 'معالجة محلية',
        limited: 'محدود',
        no: 'لا',
        yes: 'نعم',
        cloning: 'استنساخ عالي الدقة',
        notIncluded: 'غير مشمول',
        higherPlans: '(الخطط الأعلى فقط)',
        complexFees: 'رسوم استخدام معقدة',
        perMinCharges: '(رسوم بالدقيقة)',
        perFrameCharges: '(رسوم بالإطار)',
        cancelAnytime: 'إلغاء في أي وقت',
        storage: 'مساحة تخزين مشمولة',
        notSpecified: 'غير محدد',
        lifetimeOption: 'خيار خطة مدى الحياة',
        lifetimePro: '(ترخيص Pro مدى الحياة)',
        winnerTitle: 'الفائز',
        winnerSubtitle: 'للمبدعين والمحترفين',
        bestChoice: 'الخيار الأفضل',
        bestChoiceDesc: 'ميزات أكثر. سعر أفضل. أقصى قدر من الحرية.',
        expensiveLimited: 'باهظ ومحدود',
        expensiveLimitedDesc: 'دقائق محدودة. رسوم إضافية.',
        mostExpensive: 'الأغلى',
        mostExpensiveDesc: 'نموذج الدفع بالإطار. تكاليف شهرية عالية جدًا.',
        ctaTitle: 'توقف عن دفع مبالغ زائدة لدبلجة الذكاء الاصطناعي.',
        ctaDesc: 'يمنحك EasyDubbing ميزات أكثر وحرية أكبر وخيار الدفع لمرة واحدة مدى الحياة.',
        tryToday: 'جرب EasyDubbing اليوم',
        professionalDubbing: 'دبلجة ذكاء اصطناعي احترافية'
      }`
};

const originalTestimonials = [
  "testimonials: {\\n        badge: 'Trusted Worldwide',\\n        title: '10,000+ Creators Love Easy Dubbing',\\n        subtitle: 'Real results from real creators around the world.'\\n      }",
  "testimonials: {\\n        badge: 'Approuvé Mondialement',\\n        title: 'Plus de 10 000 Créateurs Adorent Easy Dubbing',\\n        subtitle: 'Des résultats réels de vrais créateurs à travers le monde.'\\n      }",
  "testimonials: {\\n        badge: 'Confianza Mundial',\\n        title: 'Más de 10.000 Creadores Aman Easy Dubbing',\\n        subtitle: 'Resultados reales de creadores reales en todo el mundo.'\\n      }",
  "testimonials: {\\n        badge: 'Fiducia Mondiale',\\n        title: 'Oltre 10.000 Creator Amano Easy Dubbing',\\n        subtitle: 'Risultati reali da veri creator in tutto il mondo.'\\n      }",
  "testimonials: {\\n        badge: 'Weltweit Vertraut',\\n        title: 'Über 10.000 Creator Lieben Easy Dubbing',\\n        subtitle: 'Echte Ergebnisse von echten Creatorn weltweit.'\\n      }",
  "testimonials: {\\n        badge: 'Доверяют во всём мире',\\n        title: 'Более 10 000 авторов любят Easy Dubbing',\\n        subtitle: 'Реальные результаты от реальных авторов по всему миру.'\\n      }",
  "testimonials: {\\n        badge: 'ثقة عالمية',\\n        title: '+10,000 مبدع يعشقون Easy Dubbing',\\n        subtitle: 'نتائج حقيقية من مبدعين حقيقيين حول العالم.'\\n      }"
];

const langs = ['en', 'fr', 'es', 'it', 'de', 'ru', 'ar'];

langs.forEach((lang, index) => {
  const original = originalTestimonials[index].replace(/\\\\n/g, '\\n');
  const replacement = original + ',\\n' + translations[lang];
  content = content.replace(original, replacement);
});

fs.writeFileSync(path, content, 'utf8');
console.log('patched successfully without breaking syntax');
