-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS activity_log (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    action text not null,       -- e.g., 'download', 'license_activated', 'admin_action'
    details text,               -- e.g., 'Windows Installer', 'user@email.com'
    country text,               -- e.g., 'US', 'FR' (2-letter code)
    ip_address text             -- just for uniqueness if needed, optional
);

-- Enable RLS (allow service role full access, public insert only if you prefer, but we'll use service role on backend)
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service Role can do anything" ON activity_log
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);
